backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: ".vuepress/public/"
public_folder: "../../"
display_url: https://comfy-concha-acf875.netlify.app